### ISSUE TITLE
Scripting does not "stick"

### ISSUE THREAD

**Issue by TomShkurti** [Zefalcon/ATSSG#44]
Even with no null-pointer issues, the scripting does not actually assign any scripts to units- the created script just stays in the GUI.

**Comment by Zefalcon** [comment]
Thank you.  I'll take a look at it.

**Comment by Zefalcon** [comment]
Should be fixed in the latest commit.  I made a stupid omission.

**Comment by TomShkurti** [comment]
Confirmed working. Now time to test the load-save functionality and watch everything blow up.

**Comment by Zefalcon** [comment]
This and #46 can be closed, then?

**Comment by TomShkurti** [comment]
Now adding multiple script elements causes weird behavior in the form of the first element used sticking and other remaining in the GUI.

**Comment by TomShkurti** [comment]
Also getting a strange IndexOutOfBounds exception when moving to (3, 1):

Action: Moving to (3,1)
Exception in thread "AWT-EventQueue-0" java.lang.ArrayIndexOutOfBoundsException: 0 >= 0
	at java.util.Vector.elementAt(Unknown Source)
	at javax.swing.DefaultListModel.getElementAt(Unknown Source)
	at ATSSG.Script.ScriptInterface.addAtPointer(ScriptInterface.java:166)
	at ATSSG.Script.ActionPopup.actionPerformed(ActionPopup.java:106)
	at java.awt.Button.processActionEvent(Unknown Source)
	at java.awt.Button.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by TomShkurti** [comment]
Also clicking on the same unit more than once causes the script to become 'stuck' to all units. I am going to have to continue testing when the interface is a bit more stable, as I currently cannot determine what is really going on with units.

**Comment by Zefalcon** [comment]
I just pushed a commit that may change that.  I have no idea what could be causing that error, though.  The line referenced literally just calls the add method of DefaultListModel.

**Comment by Zefalcon** [comment]
I'm trying to run the game myself to test things out, but for whatever reason it's taking forever to build.

**Comment by TomShkurti** [comment]
I'll have more info in maybe half an hour.

**Comment by TomShkurti** [comment]
Current most confusing bug:

when I select a unit that has a script element and close the scripting window (i.e. not by pressing update script) the element appears in all future units' script windows.

**Comment by TomShkurti** [comment]
Scripting elements also appear in all scripting windows if more than one is added at a time.

**Comment by Zefalcon** [comment]
I assume those are a result of update not getting called somewhere.  I'll see if I can track down where.

**Comment by Zefalcon** [comment]
The interface now updates every time it is opened.  I believe this should fix the bugs you're seeing.

**Comment by TomShkurti** [comment]
Ok, time for more testing.

**Comment by TomShkurti** [comment]
1. Pressing 'update script' when there is nothing added causes an exception:
Exception in thread "AWT-EventQueue-0" java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.remove(Unknown Source)
	at ATSSG.Script.ScriptInterface.internalBlock(ScriptInterface.java:220)
	at ATSSG.Script.ScriptInterface.updateScript(ScriptInterface.java:192)
	at ATSSG.Script.ScriptInterface.actionPerformed(ScriptInterface.java:150)

2. Pressing update when there IS a script does not make it stick.
3. Can add invalid "move" destinations to the list.
4. Can add invalid attack targets to the list.
5. Can set variables that don't exist yet.
6. Bunch of NYI stuff with data access, etc.

**Comment by Zefalcon** [comment]
The invalid move and attack targets should remain in, as we can't determine if they will be legal before they are performed if they're more than one action away.  We do need to re-introduce checks upon activation, however.

Setting variables that don't exist should also be caught upon update (I believe Julie's code supports it in this way)

I will investigate the script update button.  Can you confirm whether the action itself is performed or not?  If it's getting performed, it's a problem with the display; otherwise it may be a problem with how I add the script to the unit.

**Comment by TomShkurti** [comment]
Confirmed that the action is *not* being performed.

**Comment by Zefalcon** [comment]
Lovely.  I'll look into it.

**Comment by Zefalcon** [comment]
I was using a for loop to do a while loop's job.  Blame sleep-deprived me.  Problem was fixed, hopefully that was the only problem, because my manual stack trace didn't see anything else that seemed amiss.

**Comment by TomShkurti** [comment]
Nope, still not sticking. Going to check things out on my end.

**Comment by TomShkurti** [comment]
The problem seems to be in the update(Entity newEntity) function, in the if(actor != null) statement. When the turn rolls over or I click on the unit after assigning it the script (i.e. to check if the script is still there) environment is replaced by a new, empty script from newEntity.

**Comment by Zefalcon** [comment]
I'm not sure why that would do anything to the units.  The Script object itself is held by the unit, the interface just grabs that and edits it in place, or at least that's what it should be doing.

**Comment by TomShkurti** [comment]
Wait. That doesn't make sense...

**Comment by TomShkurti** [comment]
Yeah, something's strange here.

**Comment by TomShkurti** [comment]
Ok, new info. The interface is leaving ActionPerformed with the new scripting action in place. Then, by the time update() is called upon clicking the unit again, the scripting is gone. Trying to figure out what else is called between these two events.

**Comment by TomShkurti** [comment]
How are you even getting the script into the UNIT? Theres no set script method...

**Comment by Zefalcon** [comment]
It's pulling the script straight from the unit, which is then populated with a block by the interface.

**Comment by Zefalcon** [comment]
POSSIBLY we may need to directly assign the script, but it was working in the previous method, which doesn't do anything different as far as assigning the script, just the block.

**Comment by TomShkurti** [comment]
If you can give me just a moment to get git to stop being a git, I think I may have found the problem.

**Comment by TomShkurti** [comment]
It seems that the setlines method is not saving the script to the entity properly. The version I just pushed has print statements that demonstrate this fact.

**Comment by TomShkurti** [comment]
Well, also, something horrible just happened to the UnitType enum.

**Comment by Zefalcon** [comment]
Wat.  I don't even know how that's physically possible in Java.

**Comment by TomShkurti** [comment]
That was weird.

Disregard previous message.

**Comment by TomShkurti** [comment]
But yeah. Is the text output running for you?

**Comment by TomShkurti** [comment]
Sort of fixed it (and pushed), behavior is still a bit weird. Investigating.

**Comment by TomShkurti** [comment]
It's... well, MORE stable, at any rate... the only problem now with single script entities seems to be displaying _two_ of them in subsequent checks when only one was added.

**Comment by Zefalcon** [comment]
I think I found another spot things might be getting screwed up.  I'll fix that, then get back to you.

**Comment by TomShkurti** [comment]
Thanks.

**Comment by Zefalcon** [comment]
Try that one.  It was assigning environment a new script that wasn't tied to any unit.

**Comment by TomShkurti** [comment]
Nope, still duplicating.

**Comment by TomShkurti** [comment]
On 310 and 311, why is the statement being added twice?

**Comment by TomShkurti** [comment]
Actually, it looks like they alldo  that.

**Comment by Zefalcon** [comment]
It adds it to both the display and the stored list of statements.  The display has to show the user things like ifs and loops, so they have to be slightly different.

**Comment by Zefalcon** [comment]
Ah.  It should probably remove all the elements in the list before updating.

**Comment by Zefalcon** [comment]
Not sure if that will help or not, since the lists should be empty at the end of an update, but at the very least it should eliminate problems with closing the window and leaving unapplied scripts up.

**Comment by TomShkurti** [comment]
BEHOLD!! IT IS OPERATIONAL!!!

**Comment by TomShkurti** [comment]
Multiple actions are also working. Time to get started on testing the save system.

**Comment by Zefalcon** [comment]
Something still wrong?

**Comment by TomShkurti** [comment]
Going to give it awhile. If nothing comes up I'll close properly.

**Comment by TomShkurti** [comment]
I don't think anything else is going to happen tonight script-wise, so I am content to close.
